### ISSUE TITLE
Error installing llvmlite 0.34.0: FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config': 'llvm-config'

### ISSUE THREAD

**Issue by jonsnowseven** [numba/llvmlite#621]
I get this error installing llvmlite 0.34.0 in an AWS Linux AMI with python 3.6.

I understand the error but with version 0.33.0 this worked fine.

```command-line
Complete output from command /usr/local/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-1x7b09lx/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-14oz5zcs --python-tag cp36:
  running bdist_wheel
  /usr/local/bin/python3.6 /tmp/pip-install-1x7b09lx/llvmlite/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/tmp/pip-install-1x7b09lx/llvmlite/ffi/build.py", line 105, in main_posix
      out = subprocess.check_output([llvm_config, '--version'])
    File "/usr/local/lib/python3.6/subprocess.py", line 336, in check_output
      **kwargs).stdout
    File "/usr/local/lib/python3.6/subprocess.py", line 403, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/local/lib/python3.6/subprocess.py", line 709, in __init__
      restore_signals, start_new_session)
    File "/usr/local/lib/python3.6/subprocess.py", line 1344, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config': 'llvm-config'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-install-1x7b09lx/llvmlite/ffi/build.py", line 191, in <module>
      main()
    File "/tmp/pip-install-1x7b09lx/llvmlite/ffi/build.py", line 181, in main
      main_posix('linux', '.so')
    File "/tmp/pip-install-1x7b09lx/llvmlite/ffi/build.py", line 108, in main_posix
      "to the path for llvm-config" % (llvm_config,))
  RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
  error: command '/usr/local/bin/python3.6' failed with exit status 1
```

**Comment by esc** [comment]
@jonsnowseven thanks for reporting this! These kinds of errors occur when `pip` is unable to find a binary version of `llvmlite` on PyPI.  However, they may also occur if you try to compile `llvmlite` without an `llvm-config` present. Maybe you could outline what you are trying to achieve? Do you want to install a binary version of `llvmlite` from PyPi or are you trying to build `llvmlite` from source?

**Comment by LePoulpeOrange** [comment]
Hello guys, 

We have a similar issue, that's happen when we tried to install fastparquet package from PyPi (which has as dependencies numba).

The pip install command failed with the same output : 
`  ----------------------------------------
  Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite, numba, fastparquet
  Running setup.py install for llvmlite ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-7jituyay/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-wtcbsuyy/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    got version from file /tmp/pip-install-7jituyay/llvmlite/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
    running build_ext
    /usr/bin/python3 /tmp/pip-install-7jituyay/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-install-7jituyay/llvmlite/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.7/subprocess.py", line 472, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config': 'llvm-config'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/tmp/pip-install-7jituyay/llvmlite/ffi/build.py", line 191, in <module>
        main()
      File "/tmp/pip-install-7jituyay/llvmlite/ffi/build.py", line 181, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-7jituyay/llvmlite/ffi/build.py", line 108, in main_posix
        "to the path for llvm-config" % (llvm_config,))
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/usr/bin/python3' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-7jituyay/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-wtcbsuyy/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-7jituyay/llvmlite/`

**Comment by jonsnowseven** [comment]
> @jonsnowseven thanks for reporting this! These kinds of errors occur when `pip` is unable to find a binary version of `llvmlite` on PyPI. However, they may also occur if you try to compile `llvmlite` without an `llvm-config` present. Maybe you could outline what you are trying to achieve? Do you want to install a binary version of `llvmlite` from PyPi or are you trying to build `llvmlite` from source?

Sorry about that missing information, @esc. I am trying to install it with pip (from numba package).

But did something change regarding getting the OS environment configuration? Because with version 0.33.* everything works fine.

**Comment by esc** [comment]
@jonsnowseven thanks for following up. @jonsnowseven @LePoulpeOrange - it would be good if you could both add to this issue, the complete output of your `pip` commands, I need to check which version/file `pip` looks for on PyPi. The major difference that may cause this issue, is that we were no longer able to produce `manylinux1` wheels but had to upgrade to `manylinux2010` since the compiler specified in the `manylinux1` standard was too old to support compiling `LLVM 10.0.*`. The new LLVM was included in `0.34.0`. I am not sure if this upgrade is actually the issue. 

For bonus points, please also include some information about the operating system used (e.g. the output of `uname -a`) and the version of `pip`.

**Comment by LePoulpeOrange** [comment]
@esc here the complete output of pip install fastparquet: 
```
Collecting fastparquet
  Downloading https://files.pythonhosted.org/packages/28/b9/844e32d0e3739e5695057dff3a3b9f4abc0fcccff466fdaadb8fedb0ee1d/fastparquet-0.4.1.tar.gz (28.6MB)
    100% |████████████████████████████████| 28.6MB 23.8MB/s
Collecting numba>=0.28 (from fastparquet)
  Downloading https://files.pythonhosted.org/packages/cb/fd/8f75a154d45aa5ab9f2b55dba1f118f9f6ae14553912de4d4fc606fcb6e2/numba-0.51.0.tar.gz (2.1MB)
    100% |████████████████████████████████| 2.1MB 43.0MB/s
Requirement already satisfied: numpy>=1.11 in /usr/local/lib/python3.7/dist-packages (from fastparquet) (1.19.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from fastparquet) (20.4)
Requirement already satisfied: pandas>=0.19 in /usr/local/lib/python3.7/dist-packages (from fastparquet) (1.1.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from fastparquet) (1.12.0)
Requirement already satisfied: thrift>=0.11.0 in /usr/local/lib/python3.7/dist-packages (from fastparquet) (0.13.0)
Collecting llvmlite<0.35,>=0.34.0.dev0 (from numba>=0.28->fastparquet)
  Downloading https://files.pythonhosted.org/packages/0b/96/07bfa93a103fb9e3e9ae7f9f7c6687ae714aee66b6f3000da3fad71e0aa2/llvmlite-0.34.0.tar.gz (107kB)
    100% |████████████████████████████████| 112kB 22.4MB/s
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from numba>=0.28->fastparquet) (40.8.0)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->fastparquet) (2.4.7)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.19->fastparquet) (2020.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.19->fastparquet) (2.8.1)
Installing collected packages: llvmlite, numba, fastparquet
  Running setup.py install for llvmlite ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-a2zj0096/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-7iu48xqb/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    got version from file /tmp/pip-install-a2zj0096/llvmlite/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
    running build_ext
    /usr/bin/python3 /tmp/pip-install-a2zj0096/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-install-a2zj0096/llvmlite/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.7/subprocess.py", line 472, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config': 'llvm-config'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/tmp/pip-install-a2zj0096/llvmlite/ffi/build.py", line 191, in <module>
        main()
      File "/tmp/pip-install-a2zj0096/llvmlite/ffi/build.py", line 181, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-a2zj0096/llvmlite/ffi/build.py", line 108, in main_posix
        "to the path for llvm-config" % (llvm_config,))
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/usr/bin/python3' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-a2zj0096/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-7iu48xqb/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-a2zj0096/llvmlite/
```

I'm inside a container OpenJDK (8u265-slim-buster):
Linux 0ea100a9f3fc 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 GNU/Linux 

Pip version : 
**pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)**

**Comment by esc** [comment]
@LePoulpeOrange thanks for following up, it does indeed appear as though `pip` is unable to find the correct binary wheel from PyPi. Looking at the `pip` release notes for 19.0:

https://pip.pypa.io/en/stable/news/#id315

> Implement manylinux2010 platform tag support. manylinux2010 is the successor to manylinux1. It allows carefully compiled > binary wheels to be installed on compatible Linux platforms. (#5008)

It appears that `manylinux2010` support may not be available for the version of `pip` (`18.1`) that you are reporting. Would it be possible to upgrade the version of `pip` and try again?

**Comment by LePoulpeOrange** [comment]
@esc You're right ! 

With pip-20.2.2 it work fine, we had pip 18.1 because that's the version in Debian repository. Thank you for your help !

**Comment by esc** [comment]
@LePoulpeOrange excellent! Thanks for trying and confirming. @jonsnowseven did you get a chance to look into this too?

**Comment by jonsnowseven** [comment]
Hello @esc. Sorry for the delay. I am also executing `pip install fastparquet`.

So updating the pip version solves the problem? I can try it.

**Comment by esc** [comment]
@jonsnowseven yes, current estimates are that it should work with any `pip` version beyond `19.0`. If it doesn't appear to work with `20.1.1` please submit the full log output from the `pip install ...` command, thank you!

**Comment by jonsnowseven** [comment]
Sorry about that. I was using version 10.0.0, not version 20.1.1. I'll try with that pip version and post here the result.

**Comment by esc** [comment]
@jonsnowseven excellent! Good luck and do let us know how it goes.

**Comment by esc** [comment]
@jonsnowseven is there perhaps any news on this?

**Comment by jonsnowseven** [comment]
Hello @esc.

Sorry for the delay.

At the moment, I reverted llvmlite to version 0.33.0. But I tested locally with a recent pip version 19.0+ and it worked like a charm.

Regarding the AWS container, I will change the container to support recent versions of some packages and frameworks so it should work in the future. 👍

**Comment by esc** [comment]
@jonsnowseven thanks for following up. I will close this issue as I believe it has been resolved. Thank you for using Numba!

**Comment by jonsnowseven** [comment]
@esc, sure thing. Thank you for giving a follow up to this issue.

**Comment by stevesolun** [comment]
Same issue when trying to install vaex and numba:

Trying to install using pip3:

`pip3 install vaex`

Getting the following error:

```
got version from file /tmp/pip-build-4ejf0kw2/llvmlite/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
    running build_ext
    /usr/bin/python3 /tmp/pip-build-4ejf0kw2/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-build-4ejf0kw2/llvmlite/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.7/subprocess.py", line 488, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config': 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-build-4ejf0kw2/llvmlite/ffi/build.py", line 191, in <module>
        main()
      File "/tmp/pip-build-4ejf0kw2/llvmlite/ffi/build.py", line 181, in main
        main_posix('linux', '.so')
      File "/tmp/pip-build-4ejf0kw2/llvmlite/ffi/build.py", line 108, in main_posix
        "to the path for llvm-config" % (llvm_config,))
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/usr/bin/python3' failed with exit status 1
```
Here are all llvm I have:

```
libllvm-10-ocaml-dev/unknown 1:10.0.1~++20200809072545+ef32c611aa2-1~exp1~20200809173142.193 amd64
libllvm-7-ocaml-dev/bionic-updates,now 1:7-3~ubuntu0.18.04.1 amd64 [installed]
libllvm-8-ocaml-dev/bionic-updates,bionic-security 1:8-3~ubuntu18.04.2 amd64
libllvm-9-ocaml-dev/bionic-updates,bionic-security 1:9-2~ubuntu18.04.2 amd64
libllvm10/unknown,now 1:10.0.1~++20200809072545+ef32c611aa2-1~exp1~20200809173142.193 amd64 [installed,automatic]
libllvm3.9/bionic 1:3.9.1-19ubuntu1 amd64
libllvm3.9-dbg/bionic 1:3.9.1-19ubuntu1 amd64
libllvm4.0/bionic 1:4.0.1-10 amd64
libllvm4.0-dbg/bionic 1:4.0.1-10 amd64
libllvm5.0/bionic 1:5.0.1-4 amd64
libllvm5.0-dbg/bionic 1:5.0.1-4 amd64
libllvm6.0/bionic,now 1:6.0-1ubuntu2 amd64 [installed,automatic]
libllvm6.0-dbg/bionic 1:6.0-1ubuntu2 amd64
libllvm7/bionic-updates,now 1:7-3~ubuntu0.18.04.1 amd64 [installed]
libllvm8/bionic-updates,bionic-security 1:8-3~ubuntu18.04.2 amd64
libllvm9/bionic-updates,bionic-security,now 1:9-2~ubuntu18.04.2 amd64 [installed,automatic]
libstd-rust-1.24/bionic 1.24.1+dfsg1+llvm-0ubuntu2 amd64
libstd-rust-1.25/bionic-updates,bionic-security 1.25.0+dfsg1+llvm-0ubuntu1 amd64
libstd-rust-1.28/bionic-updates,bionic-security 1.28.0+dfsg1+llvm-0ubuntu1~18.04.1 amd64
libstd-rust-1.30/bionic-updates,bionic-security 1.30.0+dfsg1+llvm-2ubuntu1~18.04.1 amd64
libstd-rust-1.31/bionic-updates,bionic-security 1.31.0+dfsg1+llvm-2ubuntu1~18.04.1 amd64
libstd-rust-1.32/bionic-updates,bionic-security 1.32.0+dfsg1+llvm-1ubuntu1~18.04.1 amd64
libstd-rust-1.34/bionic-updates,bionic-security 1.34.1+dfsg2+llvm-0ubuntu1~18.04.1 amd64
libstd-rust-1.35/bionic-updates,bionic-security 1.35.0+dfsg0.1+llvm-0ubuntu1~18.04.1 amd64
libstd-rust-1.36/bionic-updates,bionic-security 1.36.0+dfsg1+llvm-2ubuntu1~18.04.1 amd64
libstd-rust-1.37/bionic-updates,bionic-security 1.37.0+dfsg1+llvm-1ubuntu1~18.04.1 amd64
libstd-rust-1.39/bionic-updates,bionic-security 1.39.0+dfsg1+llvm-3ubuntu1~18.04.1 amd64
libstd-rust-1.41/bionic-updates,bionic-security 1.41.0+dfsg1+llvm-0ubuntu1~18.04.1 amd64
libstd-rust-1.43/bionic-updates,bionic-security 1.43.0+dfsg1+llvm-1~exp1ubuntu2~18.04.1 amd64
libstd-rust-dev/bionic-updates,bionic-security 1.43.0+dfsg1+llvm-1~exp1ubuntu2~18.04.1 amd64
libstd-rust-dev-wasm32-cross/bionic-updates,bionic-security 1.41.0+dfsg1+llvm-0ubuntu1~18.04.1 all
llvm/bionic-updates 1:6.0-41~exp5~ubuntu1 amd64
llvm-10/unknown,now 1:10.0.1~++20200809072545+ef32c611aa2-1~exp1~20200809173142.193 amd64 [installed]
llvm-10-dev/unknown,now 1:10.0.1~++20200809072545+ef32c611aa2-1~exp1~20200809173142.193 amd64 [installed]
llvm-10-doc/unknown 1:10.0.1~++20200809072545+ef32c611aa2-1~exp1~20200809173142.193 all
llvm-10-examples/unknown 1:10.0.1~++20200809072545+ef32c611aa2-1~exp1~20200809173142.193 all
llvm-10-runtime/unknown,now 1:10.0.1~++20200809072545+ef32c611aa2-1~exp1~20200809173142.193 amd64 [installed,automatic]
llvm-10-tools/unknown,now 1:10.0.1~++20200809072545+ef32c611aa2-1~exp1~20200809173142.193 amd64 [installed,automatic]
llvm-3.7-doc/bionic 1:3.7.1-5ubuntu3 all
llvm-3.9/bionic 1:3.9.1-19ubuntu1 amd64
llvm-3.9-dev/bionic 1:3.9.1-19ubuntu1 amd64
llvm-3.9-doc/bionic 1:3.9.1-19ubuntu1 all
llvm-3.9-examples/bionic 1:3.9.1-19ubuntu1 all
llvm-3.9-runtime/bionic 1:3.9.1-19ubuntu1 amd64
llvm-3.9-tools/bionic 1:3.9.1-19ubuntu1 amd64
llvm-4.0/bionic 1:4.0.1-10 amd64
llvm-4.0-dev/bionic 1:4.0.1-10 amd64
llvm-4.0-doc/bionic 1:4.0.1-10 all
llvm-4.0-examples/bionic 1:4.0.1-10 all
llvm-4.0-runtime/bionic 1:4.0.1-10 amd64
llvm-4.0-tools/bionic 1:4.0.1-10 amd64
llvm-5.0/bionic 1:5.0.1-4 amd64
llvm-5.0-dev/bionic 1:5.0.1-4 amd64
llvm-5.0-doc/bionic 1:5.0.1-4 all
llvm-5.0-examples/bionic 1:5.0.1-4 all
llvm-5.0-runtime/bionic 1:5.0.1-4 amd64
llvm-5.0-tools/bionic 1:5.0.1-4 amd64
llvm-6.0/bionic 1:6.0-1ubuntu2 amd64
llvm-6.0-dev/bionic 1:6.0-1ubuntu2 amd64
llvm-6.0-doc/bionic 1:6.0-1ubuntu2 all
llvm-6.0-examples/bionic 1:6.0-1ubuntu2 all
llvm-6.0-runtime/bionic 1:6.0-1ubuntu2 amd64
llvm-6.0-tools/bionic 1:6.0-1ubuntu2 amd64
llvm-7/bionic-updates,now 1:7-3~ubuntu0.18.04.1 amd64 [installed]
llvm-7-dev/bionic-updates,now 1:7-3~ubuntu0.18.04.1 amd64 [installed]
llvm-7-doc/bionic-updates,now 1:7-3~ubuntu0.18.04.1 all [installed]
llvm-7-examples/bionic-updates,now 1:7-3~ubuntu0.18.04.1 all [installed]
llvm-7-runtime/bionic-updates,now 1:7-3~ubuntu0.18.04.1 amd64 [installed]
llvm-7-tools/bionic-updates 1:7-3~ubuntu0.18.04.1 amd64
llvm-8/bionic-updates,bionic-security 1:8-3~ubuntu18.04.2 amd64
llvm-8-dev/bionic-updates,bionic-security 1:8-3~ubuntu18.04.2 amd64
llvm-8-doc/bionic-updates,bionic-security 1:8-3~ubuntu18.04.2 all
llvm-8-examples/bionic-updates,bionic-security 1:8-3~ubuntu18.04.2 all
llvm-8-runtime/bionic-updates,bionic-security 1:8-3~ubuntu18.04.2 amd64
llvm-8-tools/bionic-updates,bionic-security 1:8-3~ubuntu18.04.2 amd64
llvm-9/bionic-updates,bionic-security,now 1:9-2~ubuntu18.04.2 amd64 [installed,automatic]
llvm-9-dev/bionic-updates,bionic-security,now 1:9-2~ubuntu18.04.2 amd64 [installed,automatic]
llvm-9-doc/bionic-updates,bionic-security 1:9-2~ubuntu18.04.2 all
llvm-9-examples/bionic-updates,bionic-security 1:9-2~ubuntu18.04.2 all
llvm-9-runtime/bionic-updates,bionic-security,now 1:9-2~ubuntu18.04.2 amd64 [installed,automatic]
llvm-9-tools/bionic-updates,bionic-security,now 1:9-2~ubuntu18.04.2 amd64 [installed,automatic]
llvm-dev/bionic-updates 1:6.0-41~exp5~ubuntu1 amd64
llvm-runtime/bionic-updates 1:6.0-41~exp5~ubuntu1 amd64
llvmlite-doc/bionic 0.19.0-2 all
python-llvmlite/bionic 0.19.0-2 amd64
python3-llvmlite/bionic 0.19.0-2 amd64
rust-doc/bionic-updates,bionic-security 1.43.0+dfsg1+llvm-1~exp1ubuntu2~18.04.1 all
rust-gdb/bionic-updates,bionic-security 1.43.0+dfsg1+llvm-1~exp1ubuntu2~18.04.1 all
rust-lldb/bionic-updates,bionic-security 1.43.0+dfsg1+llvm-1~exp1ubuntu2~18.04.1 all
rust-src/bionic-updates,bionic-security 1.43.0+dfsg1+llvm-1~exp1ubuntu2~18.04.1 all
rustc/bionic-updates,bionic-security 1.43.0+dfsg1+llvm-1~exp1ubuntu2~18.04.1 amd64
```
Please guide me how can I solve it.

**Comment by esc** [comment]
@stevesolun your `pip` is probably too old. Which version do you have? You need at least 19.0.

**Comment by stevesolun** [comment]
pip3 --version:

pip 9.0.1 from usr/lib/python3/dist-packages (python 3.7)

**Comment by esc** [comment]
@stevesolun indeed, your `pip` is too old and you will have to update it to use the latest binary wheel (0.34.0) for `llvmlite`.

**Comment by stevesolun** [comment]
The solution was to delete manually the llvm package from dist-packages (all versions), install pip (latest version) not pip3.
Right after this I have installed llvmlite 0.33.0 and numba 0.49.1.

Reinstalled vaex who reinstalled llvmlite 0.34.0 and numba 0.51 and vaex installation successfully finished!

**Comment by esc** [comment]
@stevesolun thanks for confirming!

**Comment by esc** [comment]
I will close this issue now as I believe it has been resolved. For anyone facing similar issues, please be advised that installing `llvmlite` 0.34.0 will require at least  `pip` 19.0 to be installed.

**Comment by dpoznik** [comment]
Hi, I'm getting the error described above but with `pip 20.2.4`. Any suggestions? Thanks!

```
[m|~]: pip --version
pip 20.2.4 from /Users/dpoznik/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pip (python 3.9)
[m|~]: pip install numba
Collecting numba
  Using cached numba-0.51.2.tar.gz (2.1 MB)
Collecting llvmlite<0.35,>=0.34.0.dev0
  Using cached llvmlite-0.34.0.tar.gz (107 kB)
Requirement already satisfied: numpy>=1.15 in ./.pyenv/versions/3.9.0/lib/python3.9/site-packages (from numba) (1.19.4)
Requirement already satisfied: setuptools in ./.pyenv/versions/3.9.0/lib/python3.9/site-packages (from numba) (50.3.2)
Using legacy 'setup.py install' for numba, since package 'wheel' is not installed.
Using legacy 'setup.py install' for llvmlite, since package 'wheel' is not installed.
Installing collected packages: llvmlite, numba
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/dpoznik/.pyenv/versions/3.9.0/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/3t/c_mc59bj5rgbpxbkwk6d_xq80002l1/T/pip-install-p9cjafxq/llvmlite/setup.py'"'"'; __file__='"'"'/private/var/folders/3t/c_mc59bj5rgbpxbkwk6d_xq80002l1/T/pip-install-p9cjafxq/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/3t/c_mc59bj5rgbpxbkwk6d_xq80002l1/T/pip-record-qpabqbyk/install-record.txt --single-version-externally-managed --compile --install-headers /Users/dpoznik/.pyenv/versions/3.9.0/include/python3.9/llvmlite
         cwd: /private/var/folders/3t/c_mc59bj5rgbpxbkwk6d_xq80002l1/T/pip-install-p9cjafxq/llvmlite/
    Complete output (29 lines):
    running install
    running build
    got version from file /private/var/folders/3t/c_mc59bj5rgbpxbkwk6d_xq80002l1/T/pip-install-p9cjafxq/llvmlite/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
    running build_ext
    /Users/dpoznik/.pyenv/versions/3.9.0/bin/python /private/var/folders/3t/c_mc59bj5rgbpxbkwk6d_xq80002l1/T/pip-install-p9cjafxq/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/private/var/folders/3t/c_mc59bj5rgbpxbkwk6d_xq80002l1/T/pip-install-p9cjafxq/llvmlite/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/Users/dpoznik/.pyenv/versions/3.9.0/lib/python3.9/subprocess.py", line 420, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/Users/dpoznik/.pyenv/versions/3.9.0/lib/python3.9/subprocess.py", line 501, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/Users/dpoznik/.pyenv/versions/3.9.0/lib/python3.9/subprocess.py", line 947, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/Users/dpoznik/.pyenv/versions/3.9.0/lib/python3.9/subprocess.py", line 1819, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/private/var/folders/3t/c_mc59bj5rgbpxbkwk6d_xq80002l1/T/pip-install-p9cjafxq/llvmlite/ffi/build.py", line 191, in <module>
        main()
      File "/private/var/folders/3t/c_mc59bj5rgbpxbkwk6d_xq80002l1/T/pip-install-p9cjafxq/llvmlite/ffi/build.py", line 185, in main
        main_posix('osx', '.dylib')
      File "/private/var/folders/3t/c_mc59bj5rgbpxbkwk6d_xq80002l1/T/pip-install-p9cjafxq/llvmlite/ffi/build.py", line 107, in main_posix
        raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/Users/dpoznik/.pyenv/versions/3.9.0/bin/python' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/dpoznik/.pyenv/versions/3.9.0/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/3t/c_mc59bj5rgbpxbkwk6d_xq80002l1/T/pip-install-p9cjafxq/llvmlite/setup.py'"'"'; __file__='"'"'/private/var/folders/3t/c_mc59bj5rgbpxbkwk6d_xq80002l1/T/pip-install-p9cjafxq/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/3t/c_mc59bj5rgbpxbkwk6d_xq80002l1/T/pip-record-qpabqbyk/install-record.txt --single-version-externally-managed --compile --install-headers /Users/dpoznik/.pyenv/versions/3.9.0/include/python3.9/llvmlite Check the logs for full command output.
```

**Comment by seibert** [comment]
The error you are getting is because pip cannot find a wheel of llvmlite for Python 3.9 and is trying to build llvmlite from source, which fails because LLVM cannot be found.

Jumping up a level, if you are trying to install Numba (and therefore llvmlite) into a Python 3.9 environment, you should be aware that Python 3.9 is not supported yet: https://github.com/numba/numba/issues/6345

Once Numba adds support for Python 3.9, a llvmlite wheel for Python 3.9 will also be posted at the same time, which should fix the issue you are seeing.  In the meantime, you'll have to stick with Python 3.8.

**Comment by dpoznik** [comment]
Got it. Thanks!

**Comment by solas** [comment]
I am still seeing this failure with the following combo:
python 3.8.6 (or 3.9)
macOS bigSur 11.0.1
pip 20.2.4

**Comment by esc** [comment]
@solas thank you for adding to this issue. Would you be so kind as to open a new issue? I don't think we have had any BigSur reports yet. Thanks!

**Comment by wenhaomao** [comment]
I came across similar problem, and now put my solution. My environment is, ubuntu 16, python3.5, pip-18.0.  

First, install llvm-8
> sudo apt install llvm-8-dev
Then, relink 'llvm-config'
> sudo ln -s /usr/bin/llvm-config-8 /usr/bin/llvm-config
Finally, use pip install numba
> pip install numba --user
and, succeed. 

Please check your version of 'llvm-config'
>  llvm-config --version
  8.0.0  (this is mine)

**Comment by esc** [comment]
@wenhaomao thank you for adding your solution to this issue. I must however advise strong caution for this approach as the llvmlite/numba stack requires a few custom patches for LLVM so that it works correctly, as described here: 

https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#compiling-llvm

This means, that technically a distribution based `llvm-dev` package may be unsuitable for use with llvmlite/numba.

I should additionally mention that in addition to custom patches, specific versions of llvmlite/numba need specific LLVM versions as listed here: 

https://github.com/numba/llvmlite#compatibility

As you can see, LLVM 8 is only good for llvmlite versions 0.29.0 - 0.32.0.

So, even though the approach looks like everything installed correctly as `pip` doesn't report any errors, you _may_ encounter unexpected behaviour and apparent bugs during operation -- YMMV.

**Comment by wenhaomao** [comment]
Thank you for your reminding.

**Comment by wenhaomao** [comment]
@esc Thanks for your reminding. Now I just installed numba without testing enough. I will following your advise.

**Comment by wenhaomao** [comment]
> I came across similar problem, and now put my solution. My environment is, ubuntu 16, python3.5, pip-18.0.
> 
> First, install llvm-8
> `sudo apt install llvm-8-dev`
> 
> Then, relink 'llvm-config'
> `sudo ln -s /usr/bin/llvm-config-8 /usr/bin/llvm-config`
> 
> Finally, use pip install numba
> `pip install numba --user`
> 
> and, succeed.
> 
> Please check your version of 'llvm-config'
> `llvm-config --version`
> 8.0.0 (this is mine)

My solution is not safe, please pay attention to esc's (Valentin Haenel esc) comment below my post.

**Comment by pifparfait** [comment]
> pip install numba --user
I'm following your step, but after executing pip3 install numba --user. Any help?

WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /home/pi/.cache/pip/wheels/dc/1c/6e/884fbc03f29fac1dd95a12ed0127fb286d1a9db355df15f49a/numba-0.53.1-cp37-cp37m-linux_aarch64.whl
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from numba) (56.0.0)
Requirement already satisfied: numpy>=1.15 in /home/pi/.local/lib/python3.7/site-packages (from numba) (1.20.1)
Collecting llvmlite<0.37,>=0.36.0rc1
  Using cached llvmlite-0.36.0.tar.gz (126 kB)
Building wheels for collected packages: llvmlite
  Building wheel for llvmlite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6c1se5xw/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6c1se5xw/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-n72_k7q3
       cwd: /tmp/pip-install-6c1se5xw/llvmlite/
  Complete output (11 lines):
  running bdist_wheel
  /usr/bin/python3 /tmp/pip-install-6c1se5xw/llvmlite/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/tmp/pip-install-6c1se5xw/llvmlite/ffi/build.py", line 220, in <module>
      main()
    File "/tmp/pip-install-6c1se5xw/llvmlite/ffi/build.py", line 210, in main
      main_posix('linux', '.so')
    File "/tmp/pip-install-6c1se5xw/llvmlite/ffi/build.py", line 134, in main_posix
      raise RuntimeError(msg) from None
  RuntimeError: Could not find a `llvm-config` binary. There are a number of reasons this could occur, please see: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip for help.
  error: command '/usr/bin/python3' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
DEPRECATION: Could not build wheels for llvmlite which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: llvmlite, numba
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6c1se5xw/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6c1se5xw/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-yvoeepcv/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/pi/.local/include/python3.7m/llvmlite
         cwd: /tmp/pip-install-6c1se5xw/llvmlite/
    Complete output (14 lines):
    running install
    running build
    got version from file /tmp/pip-install-6c1se5xw/llvmlite/llvmlite/_version.py {'version': '0.36.0', 'full': 'e6bb8d137d922bec8beeb01a237254778759becd'}
    running build_ext
    /usr/bin/python3 /tmp/pip-install-6c1se5xw/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-install-6c1se5xw/llvmlite/ffi/build.py", line 220, in <module>
        main()
      File "/tmp/pip-install-6c1se5xw/llvmlite/ffi/build.py", line 210, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-6c1se5xw/llvmlite/ffi/build.py", line 134, in main_posix
        raise RuntimeError(msg) from None
    RuntimeError: Could not find a `llvm-config` binary. There are a number of reasons this could occur, please see: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip for help.
    error: command '/usr/bin/python3' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6c1se5xw/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6c1se5xw/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-yvoeepcv/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/pi/.local/include/python3.7m/llvmlite Check the logs for full command output.
WARNING: You are using pip version 20.2.2; however, version 21.0.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.

**Comment by esc** [comment]
@pifparfait thank you for reporting this. As documented at https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip -- installation of binary wheels with `pip` on `aarch64` isn't supported yet. Please use `conda` as a workaround until #665 is completed, thank you.

**Comment by pifparfait** [comment]
@esc many thanks for the information. I can't use conda for some collateral issues... so I have to wait. Many thanks.
